Feature/db challenge3
sassamori/quelcode-db pull request #3
Opened 2020-11-17 10:11 UTC by sassamori

2020-11-20 13:19 UTC, n06Ar requested changes
コメントしました。
ご確認をお願いします。

SQLの実行内容については問題がないです。
Insertやupdateを使う時の注意点をコメントしました。

2020-11-20 13:19 UTC, n06Ar commented on db/db-challenge3/db-004/db-004.sql
> +(id,room_id,content,file_name,is_deleted,posted_at,post_user_id,updated_at,update_user_id)
動作に問題はないと思いますが、AUTO_INCREMENTの使っているのでidはなくても問題なさそうです。

2020-11-20 13:19 UTC, n06Ar commented on db/db-challenge3/db-004/db-004.sql
> +INSERT INTO posts
データを変更する処理の場合は、`BEGIN`と`COMMIT`のトランザクションを必ずつけるようにしてください。
複数のSQLを実行時に、いずれかで失敗した場合に`COMMIT`まで到達されなければ`ROLLBACK`で元に戻せるようにしてください。
他の箇所も確認をお願いします。

2020-11-21 00:07 UTC, sassamori commented on db/db-challenge3/db-004/db-004.sql
> +(id,room_id,content,file_name,is_deleted,posted_at,post_user_id,updated_at,update_user_id)
承知しました。
idは省略して記述していきます。

2020-11-21 00:13 UTC, sassamori commented on db/db-challenge3/db-004/db-004.sql
> +(id,room_id,content,file_name,is_deleted,posted_at,post_user_id,updated_at,update_user_id)
修正コミットのリンクです。
https://github.com/sassamori/quelcode-db/pull/3/commits/85a7af65a4943a0737acce6b98f140711cf74d9b
よろしくお願い致します。

2020-11-21 00:21 UTC, sassamori commented on db/db-challenge3/db-004/db-004.sql
> +INSERT INTO posts
修正コミットのリンクです。
https://github.com/sassamori/quelcode-db/pull/3/commits/5924d218c494491ee75258839dfd1b4815b23a2e
よろしくお願い致します。

2020-11-21 00:56 UTC, n06Ar approved these changes
LGTM!

2020-11-21 02:54 UTC, merged